#!/usr/bin python

import smtplib
#SERVER = "localhost"

FROM = 'adityasvat@gmail.com'

TO = ["asrivas7@ncsu.edu"] # must be a list

SUBJECT = "Post-commit hook executed for SE project"

TEXT = "Commit done on SE project"

# Prepare actual message

message = """\
From: %s
To: %s
Subject: %s

%s
""" % (FROM, ", ".join(TO), SUBJECT, TEXT)

# Send the mail

server = smtplib.SMTP('myserver')
server.sendmail(FROM, TO, message)
server.quit()
