#!/usr/bin/env python

import smtplib
from email.mime.text import MIMEText
from subprocess import check_output
#SERVER = "localhost"

gmail_user = 'segrp24@gmail.com'
gmail_password = 'wykbrmxaduhjvhsa'

# Get the git log --stat entry of the new commit
log = check_output(['git', 'log', '-1', '--stat', 'HEAD'])

FROM = gmail_user

TO = ['asrivas7@ncsu.edu','sbhatia6@ncsu.edu','ibanerj@ncsu.edu','dksavla@ncsu.edu','asinha6@ncsu.edu']

SUBJECT = 'Post-commit hook execution for SE project'

# Create the plaintext email message
BODY = MIMEText("Commit done on SE project :\n\n%s" % log)

email_text = """\
From: %s
To: %s
Subject: %s

%s
""" % (FROM, ", ".join(TO), SUBJECT, BODY.as_string())

try:
    # server = smtplib.SMTP('localhost')
    # server.sendmail(FROM, TO, message)
    # server.quit()
    smtp_server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
    smtp_server.ehlo()
    smtp_server.login(gmail_user, gmail_password)
    smtp_server.sendmail(FROM, TO, email_text)
    smtp_server.close()
    print ("Notification sent successfully!")
except Exception as ex:
    print ("Post-commit hook fail",ex)
