#!/usr/bin python

import smtplib
#SERVER = "localhost" hook test

gmail_user = 'segrp24@gmail.com'
gmail_password = 'wykbrmxaduhjvhsa'

FROM = gmail_user

TO = ['asrivas7@ncsu.edu']

SUBJECT = 'Post-commit hook execution for SE project'

BODY = 'Commit done on SE project"'

email_text = """\
From: %s
To: %s
Subject: %s

%s
""" % (FROM, ", ".join(TO), SUBJECT, BODY)

try:
    # server = smtplib.SMTP('localhost')
    # server.sendmail(FROM, TO, message)
    # server.quit()
    smtp_server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
    smtp_server.ehlo()
    smtp_server.login(gmail_user, gmail_password)
    smtp_server.sendmail(FROM, TO, email_text)
    smtp_server.close()
    print ("Notification sent successfully!")
except Exception as ex:
    print ("Post-commit hook fail",ex)